name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Build Svelte
        run: npm run build
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.4
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: book-tracker-d8f24
          TARGET_BRANCH: master
