name: Deploy Functions
on:
  push:
    branches:
      - master
jobs:
  main:
    name: Deploy Functions
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Deploy functions to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: book-tracker-d8f24
          TARGET_BRANCH: master
